name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        version: ['5.15.0']
        build_type: ['Release', 'Debug']

    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/Qt-${{ runner.os }}-${{ matrix.version }}
          key: ${{ runner.os }}-QtCache-${{ matrix.version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.version }}
          dir: ${{ github.workspace }}/Qt-${{ runner.os }}-${{ matrix.version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure Stringify
        run: |
          mkdir -p build
          cmake -DNETREP_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -B build -S .
        shell: bash

      - name: Build Stringify
        run: |
          cmake --build build --target "Stringify" --config "${{ matrix.build_type }}" -j

      - name: Build Tests
        run: |
          cmake --build build --target "StringifyTests" --config "${{ matrix.build_type }}" -j

      - name: Run unit tests
        run: cd build && ctest --build-config "${{ matrix.build_type }}" --progress --verbose